<script setup lang="ts">
import type Character from '~/Core/Interfaces/Character'
import type Echo from '~/Core/Interfaces/Echo'
import type Weapon from '~/Core/Interfaces/Weapon'
import ImportedEchoCard from './Cards/ImportedEchoCard.vue'

const Step = ref<number>(0)
const Scanner = useCharacterScanner()

const SelectedFile = ref<File | undefined>(undefined)
const LockImportButton = ref<boolean>(false)
const Progress = ref<ScannerStatus>(ScannerStatus.IDLE)

const ImportedCharacter = ref<Character | undefined>(undefined)
const ImportedWeapon = ref<Weapon | undefined>(undefined)
const ImportedEchoes = ref<Echo[]>([])

async function OnImportClicked() {
  if (SelectedFile.value === undefined) {
    return
  }

  await Scanner.LoadAsync(SelectedFile.value)
  const {
    character,
    weapon,
    echoes,
  } = await Scanner.ScanAsync((status) => {
    Progress.value = status

    if (Progress.value === ScannerStatus.DONE) {
      LockImportButton.value = true
    }
  })

  ImportedCharacter.value = character
  ImportedWeapon.value = weapon
  ImportedEchoes.value = echoes
  Step.value = 3
}

function GetFileObject(event: Event) {
  const input = event.target as HTMLInputElement

  if (input?.files?.[0]) {
    SelectedFile.value = input.files[0]

    // Selected file changed, enable import again.
    LockImportButton.value = false
    Progress.value = ScannerStatus.IDLE
  }
}
</script>

<template>
  <div class="mx-auto my-8 max-w-6xl text-gray-300">
    <!-- <div class="flex items-center gap-2 mx-auto">
      <canvas id="srcCanvas" width="186" height="186" />
      <canvas id="templCanvas" width="186" height="186" />
    </div> -->
    <div class="flex flex-col gap-2">
      <!-- Step 1 -->
      <div v-if="Step >= 0" v-motion-slide-left :delay="100" class="w-full flex gap-2">
        <div class="flex flex-col gap-2">
          <UBadge color="neutral" variant="solid" class="rounded-full">
            1
          </UBadge>
          <USeparator class="h-full" orientation="vertical" size="xs" />
        </div>
        <div class="mt-0.5 w-full">
          <p>Select an Image</p>
          <div class="my-8 space-y-2 text-gray-400">
            <UInput type="file" accept=".png, .jpg, .jpeg" @update:model-value="Step = 1" @change="GetFileObject" />
            <p class="text-sm">
              Please select an Image generated by the official Wuthering Waves Bot.
            </p>
          </div>
        </div>
      </div>
      <!-- Step 2 -->
      <div v-if="Step >= 1" v-motion-slide-left class="w-full flex gap-2">
        <div class="flex flex-col gap-2">
          <UBadge color="neutral" variant="solid" class="rounded-full">
            2
          </UBadge>
          <USeparator class="h-full" orientation="vertical" size="xs" />
        </div>
        <div class="mt-0.5 w-full">
          <p>Import the data.</p>
          <div class="mt-8 space-y-2">
            <UButton
              color="neutral" variant="outline"
              label="Import"
              :disabled="LockImportButton"
              @click.prevent="OnImportClicked()"
            />
            <UProgress
              v-model="Progress"
              class="w-full mt-4"
              status
              :max="['Waiting...', 'Characters...', 'Weapons...', 'Echoes...', 'Echo 1/5', 'Echo 2/5', 'Echo 3/5', 'Echo 4/5', 'Echo 5/5', 'Done!']"
            />
          </div>
        </div>
      </div>

      <!-- Step 3 -->
      <div v-if="Step >= 3" v-motion-slide-left class="w-full flex gap-2">
        <div class="flex flex-col gap-2">
          <UBadge color="neutral" variant="solid" class="rounded-full">
            3
          </UBadge>
          <USeparator class="h-full" orientation="vertical" size="xs" />
        </div>
        <div class="mt-0.5 w-full">
          <p>Verify the imported data</p>
          <div class="mb-2 mt-8 w-full grid grid-cols-4 gap-1">
            <ImportedCharacterCard
              v-if="ImportedCharacter"
              :character="ImportedCharacter"
              class="col-span-2"
            />
            <ImportedWeaponCard
              v-if="ImportedWeapon"
              :weapon="ImportedWeapon"
              class="col-span-2"
            />
          </div>
          <div class="w-full mb-8 grid grid-cols-3 gap-2">
            <ImportedEchoCard v-for="echo in ImportedEchoes" :key="echo.Id" :echo="echo" />
          </div>
        </div>
      </div>

      <!-- Step 4 -->
      <div v-if="Step >= 3" v-motion-slide-left class="w-full flex gap-2">
        <div class="flex flex-col gap-2">
          <UBadge color="neutral" variant="solid" class="rounded-full">
            4
          </UBadge>
          <USeparator class="h-full" orientation="vertical" size="xs" />
        </div>
        <div class="mt-0.5 w-full">
          <p>Confirm</p>
          <div class="my-8 space-y-4 w-full" />
        </div>
      </div>
    </div>
  </div>
</template>
