import type Echo from './Interfaces/Echo'
import { EchoCost } from './Enums/EchoCost'
import { Rarity } from './Enums/Rarity'
import { Celestial_Light, Empyrean_Anthem, Eternal_Radiance, Freezing_Frost, Frosty_Resolve, Gusts_of_Welkin, Havoc_Eclipse, Lingering_Tunes, Midnight_Veil, Molten_Rift, Moonlit_Clouds, Rejuvenating_Glow, Sierra_Gale, Tidebreaking_Courage, Void_Thunder } from './Sonatas'

export const Empty_Echo: Echo = {
  Id: -1,
  Icon: '',
  Rarity: Rarity.FIVE_STARS,
  Cost: EchoCost.FOUR_COST,
  Level: 0,
  Sonata: [],
  Statistics: [],
}

export const Echoes: Echo[] = [
  {
    Id: 6000042,
    Icon: 'Crownless_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Havoc_Eclipse,
    ],
    Statistics: [],
  },
  {
    Id: 6000084,
    Icon: 'Dragon_of_Dirge_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 6000060,
    Icon: 'Fallacy_Of_No_Return_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Rejuvenating_Glow,
    ],
    Statistics: [],
  },
  {
    Id: 6000043,
    Icon: 'Feilian_Beringal_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Sierra_Gale,
    ],
    Statistics: [],
  },
  {
    Id: 6000052,
    Icon: 'Impermanence_Heron_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Moonlit_Clouds,
      Midnight_Veil,
    ],
    Statistics: [],
  },
  {
    Id: 390080007,
    Icon: 'Inferno_Rider_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
    ],
    Statistics: [],
  },
  {
    Id: 6000044,
    Icon: 'Lampylumen_Myriad_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
    ],
    Statistics: [],
  },
  {
    Id: 6000082,
    Icon: 'Lorelei_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Midnight_Veil,
    ],
    Statistics: [],
  },
  {
    Id: 6000048,
    Icon: 'Mech_Abomination_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 6000045,
    Icon: 'Mourning_Aix_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Celestial_Light,
    ],
    Statistics: [],
  },
  {
    Id: 6000083,
    Icon: 'Sentry_Construct_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
    ],
    Statistics: [],
  },
  {
    Id: 6000039,
    Icon: 'Tempest_Mephis_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Void_Thunder,
    ],
    Statistics: [],
  },
  {
    Id: 390080003,
    Icon: 'Thundering_Mephis_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Void_Thunder,
    ],
    Statistics: [],
  },
  {
    Id: 390080005,
    Icon: 'Bell_Borne_Geochelone_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Rejuvenating_Glow,
      Moonlit_Clouds,
    ],
    Statistics: [],
  },
  {
    Id: 6000053,
    Icon: 'Dreamless_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Havoc_Eclipse,
    ],
    Statistics: [],
  },
  {
    Id: 6000085,
    Icon: 'Hecate_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Empyrean_Anthem,
    ],
    Statistics: [],
  },
  {
    Id: 6000059,
    Icon: 'Jué_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Celestial_Light,
    ],
    Statistics: [],
  },
  {
    Id: 6000086,
    Icon: 'Nightmare_Feilian_Beringal_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Sierra_Gale,
    ],
    Statistics: [],
    IsNightmare: true,
  },
  {
    Id: 6000087,
    Icon: 'Nightmare_Impermanence_Heron_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Moonlit_Clouds,
      Midnight_Veil,
    ],
    Statistics: [],
    IsNightmare: true,
  },
  {
    Id: 6000088,
    Icon: 'Nightmare_Thundering_Mephis_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Void_Thunder,
    ],
    Statistics: [],
    IsNightmare: true,
  },
  {
    Id: 6000089,
    Icon: 'Nightmare_Tempest_Mephis_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Void_Thunder,
    ],
    Statistics: [],
    IsNightmare: true,
  },
  {
    Id: 6000090,
    Icon: 'Nightmare_Crownless_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Havoc_Eclipse,
    ],
    Statistics: [],
    IsNightmare: true,
  },
  {
    Id: 6000091,
    Icon: 'Nightmare_Inferno_Rider_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
    ],
    Statistics: [],
    IsNightmare: true,
  },
  {
    Id: 6000092,
    Icon: 'Nightmare_Mourning_Aix_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
    ],
    Statistics: [],
    IsNightmare: true,
  },
  {
    Id: 6000105,
    Icon: 'Nightmare_Lampylumen_Myriad_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
    ],
    Statistics: [],
    IsNightmare: true,
  },
  {
    Id: 6000106,
    Icon: 'Reminiscence_Fleurdelys_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.FOUR_COST,
    Level: 0,
    Sonata: [
      Gusts_of_Welkin,
    ],
    Statistics: [],
  },
  {
    Id: 6000077,
    Icon: 'Abyssal_Gladius_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Midnight_Veil,
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 6000078,
    Icon: 'Abyssal_Mercator_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
      Eternal_Radiance,
    ],
    Statistics: [],
  },
  {
    Id: 6000076,
    Icon: 'Abyssal_Patricius_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
      Empyrean_Anthem,
    ],
    Statistics: [],
  },
  {
    Id: 6000049,
    Icon: 'Autopuppet_Scout_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Celestial_Light,
    ],
    Statistics: [],
  },
  {
    Id: 6000046,
    Icon: 'Carapace_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Sierra_Gale,
      Moonlit_Clouds,
    ],
    Statistics: [],
  },
  {
    Id: 390077025,
    Icon: 'Chasm_Guardian_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Rejuvenating_Glow,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 6000079,
    Icon: 'Chop_Chop_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Empyrean_Anthem,
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 6000081,
    Icon: 'Cuddle_Wuddle_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
      Midnight_Veil,
    ],
    Statistics: [],
  },
  {
    Id: 390077005,
    Icon: 'Cyan_feathered_Heron_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Sierra_Gale,
      Celestial_Light,
    ],
    Statistics: [],
  },
  {
    Id: 6000074,
    Icon: 'Diurnus_Knight_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 6000104,
    Icon: 'Capitaneus_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
      Gusts_of_Welkin,
    ],
    Statistics: [],
  },
  {
    Id: 390077022,
    Icon: 'Flautist_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Void_Thunder,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 6000056,
    Icon: 'Glacio_Dreadmane_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Moonlit_Clouds,
    ],
    Statistics: [],
  },
  {
    Id: 390077033,
    Icon: 'Havoc_Dreadmane_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
      Havoc_Eclipse,
    ],
    Statistics: [],
  },
  {
    Id: 6000040,
    Icon: 'Hoochief_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Sierra_Gale,
      Rejuvenating_Glow,
    ],
    Statistics: [],
  },
  {
    Id: 6000097,
    Icon: 'Hurriclaw_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 6000058,
    Icon: 'Lightcrusher_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Celestial_Light,
    ],
    Statistics: [],
  },
  {
    Id: 6000057,
    Icon: 'Lumiscale_Construct_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Void_Thunder,
      Freezing_Frost,
    ],
    Statistics: [],
  },
  {
    Id: 6000075,
    Icon: 'Nocturnus_Knight_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Midnight_Veil,
      Empyrean_Anthem,
    ],
    Statistics: [],
  },
  {
    Id: 6000073,
    Icon: 'Questless_Knight_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
      Midnight_Veil,
    ],
    Statistics: [],
  },
  {
    Id: 6000096,
    Icon: 'Rage_Against_The_Statue_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
    ],
    Statistics: [],
  },
  {
    Id: 390077024,
    Icon: 'Rocksteady_Guardian_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Rejuvenating_Glow,
      Celestial_Light,
    ],
    Statistics: [],
  },
  {
    Id: 390077029,
    Icon: 'Roseshroom_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Havoc_Eclipse,
    ],
    Statistics: [],
  },
  {
    Id: 390077038,
    Icon: 'Spearback_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Moonlit_Clouds,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 390077021,
    Icon: 'Stonewall_Bracer_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Rejuvenating_Glow,
      Moonlit_Clouds,
    ],
    Statistics: [],
  },
  {
    Id: 390077023,
    Icon: 'Tambourinist_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Havoc_Eclipse,
    ],
    Statistics: [],
  },
  {
    Id: 390077004,
    Icon: 'Violet_feathered_Heron_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
      Void_Thunder,
    ],
    Statistics: [],
  },
  {
    Id: 390077028,
    Icon: 'Viridblaze_Saurian_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
      Moonlit_Clouds,
    ],
    Statistics: [],
  },
  {
    Id: 6000080,
    Icon: 'Vitreum_Dancer_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.THREE_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
      Empyrean_Anthem,
    ],
    Statistics: [],
  },
  {
    Id: 390070071,
    Icon: 'Aero_Predator_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Void_Thunder,
      Sierra_Gale,
    ],
    Statistics: [],
  },
  {
    Id: 6000095,
    Icon: 'Aero_Prism_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 390070078,
    Icon: 'Baby_Viridblaze_Saurian_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
      Void_Thunder,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 6000094,
    Icon: 'Calcified_Junrock_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Tidebreaking_Courage,
      Empyrean_Anthem,
    ],
    Statistics: [],
  },
  {
    Id: 6000072,
    Icon: 'Chest_Mimic_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
      Midnight_Veil,
      Empyrean_Anthem,
    ],
    Statistics: [],
  },
  {
    Id: 6000047,
    Icon: 'Chirpuff_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Sierra_Gale,
      Havoc_Eclipse,
    ],
    Statistics: [],
  },
  {
    Id: 7,
    Icon: 'Chop_Chop_Headless_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 8,
    Icon: 'Chop_Chop_Leftless_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 9,
    Icon: 'Chop_Chop_Rightless_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 6000051,
    Icon: 'Clang_Bang_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Celestial_Light,
      Freezing_Frost,
    ],
    Statistics: [],
  },
  {
    Id: 390070074,
    Icon: 'Cruisewing_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Celestial_Light,
      Rejuvenating_Glow,
      Moonlit_Clouds,
    ],
    Statistics: [],
  },
  {
    Id: 6000041,
    Icon: 'Diamondclaw_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Moonlit_Clouds,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 6000071,
    Icon: 'Diggy_Duggy_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 6000055,
    Icon: 'Dwarf_Cassowary_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Sierra_Gale,
      Rejuvenating_Glow,
    ],
    Statistics: [],
  },
  {
    Id: 390070053,
    Icon: 'Electro_Predator_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
      Void_Thunder,
    ],
    Statistics: [],
  },
  {
    Id: 390070077,
    Icon: 'Excarat_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Havoc_Eclipse,
    ],
    Statistics: [],
  },
  {
    Id: 6000067,
    Icon: 'Fae_Ignis_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
      Midnight_Veil,
    ],
    Statistics: [],
  },
  {
    Id: 390070052,
    Icon: 'Fission_Junrock_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Void_Thunder,
      Rejuvenating_Glow,
      Moonlit_Clouds,
    ],
    Statistics: [],
  },
  {
    Id: 6000063,
    Icon: 'Frostscourge_Stalker_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
      Midnight_Veil,
    ],
    Statistics: [],
  },
  {
    Id: 390070100,
    Icon: 'Fusion_Dreadmane_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
      Rejuvenating_Glow,
    ],
    Statistics: [],
  },
  {
    Id: 390077012,
    Icon: 'Fusion_Prism_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Molten_Rift,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 390070064,
    Icon: 'Fusion_Warrior_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
      Void_Thunder,
      Sierra_Gale,
    ],
    Statistics: [],
  },
  {
    Id: 6000061,
    Icon: 'Galescourge_Stalker_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
      Empyrean_Anthem,
    ],
    Statistics: [],
  },
  {
    Id: 390070070,
    Icon: 'Glacio_Predator_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Celestial_Light,
    ],
    Statistics: [],
  },
  {
    Id: 390077013,
    Icon: 'Glacio_Prism_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Havoc_Eclipse,
      Moonlit_Clouds,
    ],
    Statistics: [],
  },
  {
    Id: 6000093,
    Icon: 'Golden_Junrock_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Eternal_Radiance,
      Frosty_Resolve,
    ],
    Statistics: [],
  },
  {
    Id: 390070076,
    Icon: 'Gulpuff_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Celestial_Light,
    ],
    Statistics: [],
  },
  {
    Id: 390077017,
    Icon: 'Havoc_Prism_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Void_Thunder,
      Celestial_Light,
      Havoc_Eclipse,
    ],
    Statistics: [],
  },
  {
    Id: 390070065,
    Icon: 'Havoc_Warrior_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Celestial_Light,
      Havoc_Eclipse,
    ],
    Statistics: [],
  },
  {
    Id: 390070105,
    Icon: 'Hoartoise_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Celestial_Light,
    ],
    Statistics: [],
  },
  {
    Id: 6000069,
    Icon: 'Hocus_Pocus_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
      Empyrean_Anthem,
    ],
    Statistics: [],
  },
  {
    Id: 6000038,
    Icon: 'Hooscamp_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Sierra_Gale,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 6000054,
    Icon: 'Lava_Larva_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Lingering_Tunes,
      Molten_Rift,
    ],
    Statistics: [],
  },
  {
    Id: 6000070,
    Icon: 'Lottie_Lost_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Frosty_Resolve,
      Tidebreaking_Courage,
    ],
    Statistics: [],
  },
  {
    Id: 6000068,
    Icon: 'Nimbus_Wraith_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Midnight_Veil,
      Empyrean_Anthem,
    ],
    Statistics: [],
  },
  {
    Id: 390070075,
    Icon: 'Sabyr_Boar_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Freezing_Frost,
      Sierra_Gale,
      Moonlit_Clouds,
    ],
    Statistics: [],
  },
  {
    Id: 390070066,
    Icon: 'Snip_Snap_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
      Rejuvenating_Glow,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 390077016,
    Icon: 'Spectro_Prism_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
      Void_Thunder,
      Celestial_Light,
    ],
    Statistics: [],
  },
  {
    Id: 390070069,
    Icon: 'Tick_Tack_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Havoc_Eclipse,
      Rejuvenating_Glow,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 6000050,
    Icon: 'Traffic_Illuminator_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Molten_Rift,
      Void_Thunder,
      Sierra_Gale,
    ],
    Statistics: [],
  },
  {
    Id: 390070051,
    Icon: 'Vanguard_Junrock_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Void_Thunder,
      Rejuvenating_Glow,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 6000062,
    Icon: 'Voltscourge_Stalker_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Midnight_Veil,
      Empyrean_Anthem,
    ],
    Statistics: [],
  },
  {
    Id: 390070068,
    Icon: 'Whiff_Whaff_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Rejuvenating_Glow,
      Moonlit_Clouds,
      Sierra_Gale,
    ],
    Statistics: [],
  },
  {
    Id: 390070079,
    Icon: 'Young_Roseshroom_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Sierra_Gale,
      Havoc_Eclipse,
    ],
    Statistics: [],
  },
  {
    Id: 390070067,
    Icon: 'Zig_Zag_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Celestial_Light,
      Moonlit_Clouds,
      Lingering_Tunes,
    ],
    Statistics: [],
  },
  {
    Id: 6000098,
    Icon: 'La_Guardia_Icon.webp',
    Rarity: Rarity.FIVE_STARS,
    Cost: EchoCost.ONE_COST,
    Level: 0,
    Sonata: [
      Midnight_Veil,
      Gusts_of_Welkin,
    ],
    Statistics: [],
  },
]

export const TemplateEchoes: Echo[] = Echoes
