export const AppName = 'WuWa Optimizer'
export const AppDescription = 'Wuwa Optimizer by Mikyan'
export const GameVersion = '2.3'
export const UpcomingGameVersion = '2.3'
export const ScorerGameVersion = '2.3'
export const RotationBuilderGameVersion = '2.0'
export const AppVersion = '0.0.1'
