import type Weapon from './Interfaces/Weapon'
import { Rarity } from './Enums/Rarity'
import { StatType } from './Enums/StatType'
import { WeaponType } from './Enums/WeaponType'

export const Weapons: Weapon[] = [
  {
    Id: 21010011,
    Name: 'Training Broadblade',
    Icon: 'Training_Broadblade_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.ONE_STAR,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 250.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 11.47,
    },
  },
  {
    Id: 21010012,
    Name: 'Tyro Broadblade',
    Icon: 'Tyro_Broadblade_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.TWO_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 275.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 14.85,
    },
  },
  {
    Id: 21010013,
    Name: 'Broadblade Of Night',
    Icon: 'Broadblade_Of_Night_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 325.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 24.3,
    },
  },
  {
    Id: 21010015,
    Name: 'Lustrous Razor',
    Icon: 'Lustrous_Razor_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 36.45,
    },
  },
  {
    Id: 21010016,
    Name: 'Verdant Summit',
    Icon: 'Verdant_Summit_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_DMG,
      Value: 48.6,
    },
  },
  {
    Id: 21010023,
    Name: 'Originite: Type I',
    Icon: 'Originite_Type_I_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.DEF_PERCENTAGE,
      Value: 38.48,
    },
  },
  {
    Id: 21010024,
    Name: 'Discord',
    Icon: 'Discord_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 337.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 51.84,
    },
  },
  {
    Id: 21010026,
    Name: 'Ages Of Harvest',
    Icon: 'Ages_Of_Harvest_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 24.3,
    },
  },
  {
    Id: 21010034,
    Name: 'Broadblade#41',
    Icon: 'Broadblade41_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 32.4,
    },
  },
  {
    Id: 21010036,
    Name: 'Wildfire Mark',
    Icon: 'Wildfire_Mark_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_DMG,
      Value: 48.6,
    },
  },
  {
    Id: 21010043,
    Name: 'Broadblade Of Voyager',
    Icon: 'Broadblade_Of_Voyager_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 32.4,
    },
  },
  {
    Id: 21010044,
    Name: 'Dauntless Evernight',
    Icon: 'Dauntless_Evernight_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 337.5,
    },
    SecondaryStatistic: {
      Type: StatType.DEF_PERCENTAGE,
      Value: 61.56,
    },
  },
  {
    Id: 21010053,
    Name: 'Guardian Broadblade',
    Icon: 'Guardian_Broadblade_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 325.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 24.3,
    },
  },
  {
    Id: 21010063,
    Name: 'Beguiling Melody',
    Icon: 'Beguiling_Melody_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21010064,
    Name: 'Helios Cleaver',
    Icon: 'Helios_Cleaver_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21010074,
    Name: 'Autumntrace',
    Icon: 'Autumntrace_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 20.25,
    },
  },
  {
    Id: 21010084,
    Name: 'Waning Redshift',
    Icon: 'Waning_Redshift_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21010094,
    Name: 'Meditations On Mercy',
    Icon: 'Meditations_On_Mercy_Icon.webp',
    Type: WeaponType.BROADBLADE,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21020011,
    Name: 'Training Sword',
    Icon: 'Training_Sword_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.ONE_STAR,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 250.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 11.47,
    },
  },
  {
    Id: 21020012,
    Name: 'Tyro Sword',
    Icon: 'Tyro_Sword_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.TWO_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 275.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 14.85,
    },
  },
  {
    Id: 21020013,
    Name: 'Sword Of Night',
    Icon: 'Sword_Of_Night_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 325.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 24.3,
    },
  },
  {
    Id: 21020015,
    Name: 'Emerald Of Genesis',
    Icon: 'Emerald_Of_Genesis_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 24.3,
    },
  },
  {
    Id: 21020016,
    Name: 'Blazing Brilliance',
    Icon: 'Blazing_Brilliance_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_DMG,
      Value: 48.6,
    },
  },
  {
    Id: 21020017,
    Name: 'Somnoire Anchor',
    Icon: 'Somnoire_Anchor_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21020023,
    Name: 'Originite: Type Ii',
    Icon: 'Originite_Type_Ii_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 325.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 24.3,
    },
  },
  {
    Id: 21020024,
    Name: 'Overture',
    Icon: 'Overture_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 337.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 51.84,
    },
  },
  {
    Id: 21020026,
    Name: 'Red Spring',
    Icon: 'Red_Spring_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 24.3,
    },
  },
  {
    Id: 21020034,
    Name: 'Sword#18',
    Icon: 'Sword18_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 387.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 36.45,
    },
  },
  {
    Id: 21020036,
    Name: 'Unflickering Valor',
    Icon: 'Unflickering_Valor_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 77.04,
    },
  },
  {
    Id: 21020043,
    Name: 'Sword Of Voyager',
    Icon: 'Sword_Of_Voyager_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 32.4,
    },
  },
  {
    Id: 21020044,
    Name: 'Commando Of Conviction',
    Icon: 'Commando_Of_Conviction_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21020046,
    Name: 'Bloodpact\'s Pledge',
    Icon: 'Bloodpacts_Pledge_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 38.88,
    },
  },
  {
    Id: 21020053,
    Name: 'Guardian Sword',
    Icon: 'Guardian_Sword_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.HP_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21020056,
    Name: 'Defier\'s Thorn',
    Icon: 'Defiers_Thorn_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.HP_PERCENTAGE,
      Value: 72.23,
    },
  },
  {
    Id: 21020064,
    Name: 'Lunar Cutter',
    Icon: 'Lunar_Cutter_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21020074,
    Name: 'Lumingloss',
    Icon: 'Lumingloss_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 387.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 36.45,
    },
  },
  {
    Id: 21020084,
    Name: 'Endless Collapse',
    Icon: 'Endless_Collapse_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21020094,
    Name: 'Fables Of Wisdom',
    Icon: 'Fables_Of_Wisdom_Icon.webp',
    Type: WeaponType.SWORD,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21030011,
    Name: 'Training Pistols',
    Icon: 'Training_Pistols_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.ONE_STAR,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 250.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 11.47,
    },
  },
  {
    Id: 21030012,
    Name: 'Tyro Pistols',
    Icon: 'Tyro_Pistols_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.TWO_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 275.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 14.85,
    },
  },
  {
    Id: 21030013,
    Name: 'Pistols Of Night',
    Icon: 'Pistols_Of_Night_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 325.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 24.3,
    },
  },
  {
    Id: 21030015,
    Name: 'Static Mist',
    Icon: 'Static_Mist_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 24.3,
    },
  },
  {
    Id: 21030016,
    Name: 'The Last Dance',
    Icon: 'The_Last_Dance_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 500.0,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_DMG,
      Value: 72.0,
    },
  },
  {
    Id: 21030023,
    Name: 'Originite: Type Iii',
    Icon: 'Originite_Type_Iii_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 325.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 24.3,
    },
  },
  {
    Id: 21030024,
    Name: 'Cadenza',
    Icon: 'Cadenza_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 337.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 51.84,
    },
  },
  {
    Id: 21030026,
    Name: 'Woodland Aria',
    Icon: 'Woodland_Aria_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 500.0,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 36.0,
    },
  },
  {
    Id: 21030034,
    Name: 'Pistols#26',
    Icon: 'Pistols26_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 387.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 36.45,
    },
  },
  {
    Id: 21030043,
    Name: 'Pistols Of Voyager',
    Icon: 'Pistols_Of_Voyager_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21030044,
    Name: 'Undying Flame',
    Icon: 'Undying_Flame_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21030053,
    Name: 'Guardian Pistols',
    Icon: 'Guardian_Pistols_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21030064,
    Name: 'Novaburst',
    Icon: 'Novaburst_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21030074,
    Name: 'Thunderbolt',
    Icon: 'Thunderbolt_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 387.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 36.45,
    },
  },
  {
    Id: 21030084,
    Name: 'Relativistic Jet',
    Icon: 'Relativistic_Jet_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21030094,
    Name: 'Romance In Farewell',
    Icon: 'Romance_In_Farewell_Icon.webp',
    Type: WeaponType.PISTOLS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21040011,
    Name: 'Training Gauntlets',
    Icon: 'Training_Gauntlets_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.ONE_STAR,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 250.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 11.47,
    },
  },
  {
    Id: 21040012,
    Name: 'Tyro Gauntlets',
    Icon: 'Tyro_Gauntlets_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.TWO_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 275.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 14.85,
    },
  },
  {
    Id: 21040013,
    Name: 'Gauntlets Of Night',
    Icon: 'Gauntlets_Of_Night_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 325.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 24.3,
    },
  },
  {
    Id: 21040015,
    Name: 'Abyss Surges',
    Icon: 'Abyss_Surges_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 36.45,
    },
  },
  {
    Id: 21040016,
    Name: 'Verity\'s Handle',
    Icon: 'Veritys_Handle_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 24.3,
    },
  },
  {
    Id: 21040023,
    Name: 'Originite: Type Iv',
    Icon: 'Originite_Type_Iv_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_DMG,
      Value: 40.5,
    },
  },
  {
    Id: 21040024,
    Name: 'Marcato',
    Icon: 'Marcato_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 337.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 51.84,
    },
  },
  {
    Id: 21040026,
    Name: 'Tragicomedy',
    Icon: 'Tragicomedy_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 24.3,
    },
  },
  {
    Id: 21040034,
    Name: 'Gauntlets#21d',
    Icon: 'Gauntlets21d_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 387.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 38.88,
    },
  },
  {
    Id: 21040036,
    Name: 'Blazing Justice',
    Icon: 'Blazing_Justice_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_DMG,
      Value: 48.6,
    },
  },
  {
    Id: 21040043,
    Name: 'Gauntlets Of Voyager',
    Icon: 'Gauntlets_Of_Voyager_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 325.0,
    },
    SecondaryStatistic: {
      Type: StatType.DEF_PERCENTAGE,
      Value: 30.78,
    },
  },
  {
    Id: 21040044,
    Name: 'Amity Accord',
    Icon: 'Amity_Accord_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 337.5,
    },
    SecondaryStatistic: {
      Type: StatType.DEF_PERCENTAGE,
      Value: 61.56,
    },
  },
  {
    Id: 21040053,
    Name: 'Guardian Gauntlets',
    Icon: 'Guardian_Gauntlets_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.DEF_PERCENTAGE,
      Value: 38.48,
    },
  },
  {
    Id: 21040064,
    Name: 'Hollow Mirage',
    Icon: 'Hollow_Mirage_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21040074,
    Name: 'Stonard',
    Icon: 'Stonard_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 20.25,
    },
  },
  {
    Id: 21040084,
    Name: 'Celestial Spiral',
    Icon: 'Celestial_Spiral_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21040094,
    Name: 'Legend Of Drunken Hero',
    Icon: 'Legend_Of_Drunken_Hero_Icon.webp',
    Type: WeaponType.GAUNTLETS,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21050011,
    Name: 'Training Rectifier',
    Icon: 'Training_Rectifier_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.ONE_STAR,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 250.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 11.47,
    },
  },
  {
    Id: 21050012,
    Name: 'Tyro Rectifier',
    Icon: 'Tyro_Rectifier_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.TWO_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 275.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 14.85,
    },
  },
  {
    Id: 21050013,
    Name: 'Rectifier Of Night',
    Icon: 'Rectifier_Of_Night_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 325.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 24.3,
    },
  },
  {
    Id: 21050015,
    Name: 'Cosmic Ripples',
    Icon: 'Cosmic_Ripples_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 500.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 54.0,
    },
  },
  {
    Id: 21050016,
    Name: 'Stringmaster',
    Icon: 'Stringmaster_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 500.0,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 36.0,
    },
  },
  {
    Id: 21050017,
    Name: 'Call Of The Abyss',
    Icon: 'Call_Of_The_Abyss_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 337.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 51.84,
    },
  },
  {
    Id: 21050023,
    Name: 'Originite: Type V',
    Icon: 'Originite_Type_V_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.HP_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21050024,
    Name: 'Variation',
    Icon: 'Variation_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 337.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 51.84,
    },
  },
  {
    Id: 21050026,
    Name: 'Rime Draped Sprouts',
    Icon: 'Rime_Draped_Sprouts_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 500.0,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_DMG,
      Value: 72.0,
    },
  },
  {
    Id: 21050027,
    Name: 'Ocean\'s Gift',
    Icon: 'Oceans_Gift_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21050034,
    Name: 'Rectifier#25',
    Icon: 'Rectifier25_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 337.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 51.84,
    },
  },
  {
    Id: 21050036,
    Name: 'Stellar Symphony',
    Icon: 'Stellar_Symphony_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 77.04,
    },
  },
  {
    Id: 21050043,
    Name: 'Rectifier Of Voyager',
    Icon: 'Rectifier_Of_Voyager_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 300.0,
    },
    SecondaryStatistic: {
      Type: StatType.ENERGY_REGENERATION,
      Value: 32.4,
    },
  },
  {
    Id: 21050044,
    Name: 'Jinzhou Keeper',
    Icon: 'Jinzhou_Keeper_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 387.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 36.45,
    },
  },
  {
    Id: 21050046,
    Name: 'Luminous Hymn',
    Icon: 'Luminous_Hymn_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 500.0,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 36.0,
    },
  },
  {
    Id: 21050053,
    Name: 'Guardian Rectifier',
    Icon: 'Guardian_Rectifier_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.THREE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 325.0,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 24.3,
    },
  },
  {
    Id: 21050056,
    Name: 'Whispers Of Sirens',
    Icon: 'Whispers_Of_Sirens_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 500.0,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_DMG,
      Value: 72.0,
    },
  },
  {
    Id: 21050064,
    Name: 'Comet Flare',
    Icon: 'Comet_Flare_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.HP_PERCENTAGE,
      Value: 30.38,
    },
  },
  {
    Id: 21050066,
    Name: 'Lethean Elegy',
    Icon: 'Lethean_Elegy_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FIVE_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 587.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 24.3,
    },
  },
  {
    Id: 21050074,
    Name: 'Augment',
    Icon: 'Augment_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 412.5,
    },
    SecondaryStatistic: {
      Type: StatType.CRIT_RATE,
      Value: 20.25,
    },
  },
  {
    Id: 21050084,
    Name: 'Fusion Accretion',
    Icon: 'Fusion_Accretion_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
  {
    Id: 21050094,
    Name: 'Waltz In Masquerade',
    Icon: 'Waltz_In_Masquerade_Icon.webp',
    Type: WeaponType.RECTIFIER,
    Rarity: Rarity.FOUR_STARS,
    Level: 0,
    Rank: 1,
    MainStatistic: {
      Type: StatType.ATTACK,
      Value: 462.5,
    },
    SecondaryStatistic: {
      Type: StatType.ATTACK_PERCENTAGE,
      Value: 18.23,
    },
  },
]

export const TemplateWeapons: Weapon[] = Weapons
